### ISSUE TITLE
ignore transient fields

### ISSUE THREAD

**Issue by SebastianDietrich** [jqno/equalsverifier#111] opened 2015-04-18 22:02 UTC
I've got a class that has (amongst others) a private transient field (@Autowired by spring).
This class relies on EqualsBuilder.reflectionEquals() and HashCodeBuilder.reflectionHashCode() (both ignore transient fields).

When testing with EqualsVerifier, I get a recursive datastructure exception mentioning amongst others this field.

**Comment by jqno** [comment] 2015-04-19 13:00
Hi Sebastian,

Even though a field is marked transient, EqualsVerifier still has to deal with it. It can't leave the field null, because that might cause a NullPointerException somewhere. Therefore, it will still try to come up with values for these fields. The only thing it doesn't do, is complain if you forget to use it in an equals or hashCode method. Therefore, it looks like you still need to provide a prefab value.

If you give me some example code that reproduces the problem, I may be able to help you further.

Jan

**Comment by jqno** [comment] 2015-07-04 13:57
Hi Sebastian, I was going through the issues and noticed this is one was still open. Do you have some sample code for me? Otherwise, I'll probably close this issue later.

**Comment by jqno** [comment] 2015-08-29 14:10
I'm going to close this issue now. Feel free to re-open it if you have more information.

**Closed as completed by jqno** 2015-08-29 14:10 UTC
Labels: needs more information
