### ISSUE TITLE
Illegal reflective access on Java 11

### ISSUE THREAD

**Issue by PunitaGosar-QHR** [jqno/equalsverifier#393] opened 2021-02-11 19:46 UTC
**Describe the bug**
Getting a warning about illegal reflective access operation when running unit test using JUnit 5

**To Reproduce**
Testing immutability of a class using 
```
EqualsVerifier.forClass(classToTest)
        .withPrefabValues(Color.class,
            new Color(43, 43, 54, 43),
            new Color(2, 43, 54, 44))
        .verify();
```

**Code that triggers the behavior**

Testing class :
```
import java.awt.Color;
import nl.jqno.equalsverifier.EqualsVerifier;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

public abstract class AbstractImmutableModelTest {
  protected static Set<Class<?>> classesToTest = new HashSet<>();

  protected static Stream<Arguments> getClasses() {
    return classesToTest.stream().map(Arguments::of).collect(Collectors.toSet()).stream();
  }

  @ParameterizedTest
  @MethodSource("getClasses")
  public void testEquals(Class<?> classToTest) {
    EqualsVerifier.forClass(classToTest)
        .withPrefabValues(Color.class,
            new Color(43, 43, 54, 43),
            new Color(2, 43, 54, 44))
        .verify();
  }
}
```

Test class :
```
import org.junit.jupiter.api.BeforeAll;

public class ImmutableDriveTest extends AbstractImmutableModelTest {
  @BeforeAll
  static void setUp() {
    classesToTest.clear();
    classesToTest.add(ImmutableExample.class);
  }
}
```
Example class :
```
import com.annotations.Immutable;
import java.util.Objects;

@Immutable
public final class ImmutableExample {

  private final int number;
  private final String data;

  public ImmutableExample(int number, String data) {
    this.number = number;
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImmutableExample that = (ImmutableExample) o;
    return number == that.number &&
        Objects.equals(data, that.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, data);
  }
}
```

**Error message**

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier (file:/C:/Users/<user_name>/.m2/repository/nl/jqno/equalsverifier/equalsverifier/3.5.3/equalsverifier-3.5.3.jar) to field java.awt.Color.value
WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldModifier
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Expected behavior**
There should be no warning

**Version**
3.5.3

**Additional context**
This is an existing code and we are upgrading to JUnit 5.

**Comment by jqno** [comment] 2021-02-12 08:43
Am I understanding correctly that you are testing `java.awt.Color` itself? May I ask why?

I can reproduce this issue when applying calling `EqualsVerifier.forClass(Color.class).verify()`, but not when calling EqualsVerifier on some class that merely has a field of type `Color`.

**Comment by PunitaGosar-QHR** [comment] 2021-02-18 18:32
I am not testing `java.awt.Color`. The test is for an immutable class. It is a legacy code. `classToTest` will be a model class that must be immutable for the test to pass, for example `ImmutableExample`.

**Comment by jqno** [comment] 2021-02-19 07:32
I have copied all of your code into my IDE, and the test passes without any issues, so there must be something else going on. EqualsVerifier already has prefab values for `java.awt.Color` built-in (which also means that you can remove that line from your test if you want, BTW!), so the only way that I can think of that causes the error that you report, is if you (perhaps accidentally) call `EqualsVerfier.forClass(Color.class).verify()` somewhere. But I don't know your code, so there can be something else that I'm missing.

**Comment by Bananeweizen** [comment] 2021-03-06 18:38
I see the same warning on a custom subclass of AbstractList, using version 3.5.0 currently. So please try this one:
```
final class MyList extends AbstractList<String> {
    final String foobar = "42";

    @Override
    public String get(final int index) {
        return "something";
    }

    @Override
    public int size() {
        return foobar.length();
    }
}

@Test
void test() {
    EqualsVerifier.forClass(MyList.class).verify();
}

```
For me that gives
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier to field java.util.AbstractList.modCount

```

**Comment by jqno** [comment] 2021-03-08 07:23
The cause of that illegal reflective access warning is different from the one the OP mentioned.

Unfortunately, there's not good way to fix this one. When you're testing a class with fields from a different module, EqualsVerifier tries to instantiate them using reflection (which causes a warning), but otherwise leaves them alone. Adding a prefab value will fix that. EqualsVerifier includes loads of prefab values for Java API classes so you don't have to give them manually.

However, you are actually extending a class from another module. EqualsVerifier will try to use reflection to change its fields no matter what: a prefab value isn't going to help here. So the only way to make this warning go away, is to actually open up the `java.util` module for reflection in your tests.

**Comment by PunitaGosar-QHR** [comment] 2021-03-08 16:36
> I have copied all of your code into my IDE, and the test passes without any issues, so there must be something else going on. EqualsVerifier already has prefab values for `java.awt.Color` built-in (which also means that you can remove that line from your test if you want, BTW!), so the only way that I can think of that causes the error that you report, is if you (perhaps accidentally) call `EqualsVerfier.forClass(Color.class).verify()` somewhere. But I don't know your code, so there can be something else that I'm missing.

Thank you for looking into it. The tests do pass. The only issue here is that I get the warnings about illegal reflective access. It's not a breaking issue and since it's a legacy code, we can make do with the warnings. I just wanted to check if there is any solution to this warning issue.

**Comment by jqno** [comment] 2021-03-09 08:36
Well, the only way that I know of for this particular warning (`WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldModifier (file:...) to field java.awt.Color.value`) is when there's an explicit EqualsVerifier test of `java.awt.Color` somewhere: something like `EqualsVerifier.forClass(Color.class).verify()`. If that's not the case, I would need much more information about your codebase to help you remove the warning, because with the code you posted, the warning doesn't occur.

If it's not that important to you, you can close the issue if you like.

**Closed as completed** 2021-05-26 06:38 UTC
