### ISSUE TITLE
specify fields that can't be null

### ISSUE THREAD

**Issue by xenoterracide** [jqno/equalsverifier#164] opened 2016-12-21 13:43 UTC
# What steps will reproduce the problem?

create an object with a constructor with final fields, and throw an exception in constructor if fields are null.

# What is the code that triggers this problem?

https://github.com/spring-projects/spring-security/blob/f432c04/core/src/main/java/org/springframework/security/core/userdetails/User.java#L202

you'll note that the constructor checks for nulls, and throws if it is null

# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: Non-nullity: equals throws NullPointerException on field username.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages

	at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:367)
	at com.xenoterracide.rpf.security.IdentifiedUserDetailsTest.testEquals(IdentifiedUserDetailsTest.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at org.springframework.security.core.userdetails.User.equals(User.java:197)
	at com.xenoterracide.rpf.security.IdentifiedUserDetails.equals(IdentifiedUserDetails.java:30)
	at nl.jqno.equalsverifier.NullChecker$NullPointerExceptionFieldCheck$2.run(NullChecker.java:85)
	at nl.jqno.equalsverifier.NullChecker$NullPointerExceptionFieldCheck.handle(NullChecker.java:99)
	at nl.jqno.equalsverifier.NullChecker$NullPointerExceptionFieldCheck.performTests(NullChecker.java:81)
	at nl.jqno.equalsverifier.NullChecker$NullPointerExceptionFieldCheck.execute(NullChecker.java:67)
	at nl.jqno.equalsverifier.FieldInspector.check(FieldInspector.java:40)
	at nl.jqno.equalsverifier.NullChecker.check(NullChecker.java:45)
	at nl.jqno.equalsverifier.EqualsVerifier.verifyWithoutExamples(EqualsVerifier.java:405)
	at nl.jqno.equalsverifier.EqualsVerifier.performVerification(EqualsVerifier.java:391)
	at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:364)
	... 23 more
```

# What did you expect?

more or less this, but what I think is that there should be a method `fieldsThatCan'tBeNull( "username" )`  (early morning api suggestion, open to other naming) so that equalsverifer doesn't test that field with a null. Obviously I will resolve this for now using `Warning.NULL_FIELDS` but that will suppress for all fields and thus would miss any additional bugs.

# Which version of EqualsVerifier are you using?

2.1.6

# Please provide any additional information below.

Also the docs could be better and suggest `Objects.equals(...)` which was added in Java 7 and is null safe.

http://jqno.nl/equalsverifier/errormessages/non-nullity-equals-hashcode-tostring-throws-nullpointerexception/

**Comment by jqno** [comment] 2016-12-21 20:53
I'm closing this, because it's a duplicate of #134.
I've updated the documentation as requested.

**Closed as completed by jqno** 2016-12-21 20:53 UTC
Labels: duplicate
