### ISSUE TITLE
Illegal reflective access with Java 9/10

### ISSUE THREAD

**Issue by don-vip** [jqno/equalsverifier#183] opened 2018-01-16 02:25 UTC
# What steps will reproduce the problem?

1. [Like this tweet](https://twitter.com/jqno/status/951484885310627841), because it's a major effort, congrats!
2. Run JOSM unit test `org.openstreetmap.josm.data.gpx.WayPointTest` with [jdk-10-ea+39](http://jdk.java.net/10/)
3. Notice warning about illegal reflective access operation in logs

# What is the code that triggers this problem?
```java
package org.openstreetmap.josm.data.gpx;
import java.awt.color.ColorSpace;
public class WayPointTest {
    @Test
    public void testEqualsContract() {
        EqualsVerifier.forClass(WayPoint.class).usingGetClass()
            .suppress(Warning.NONFINAL_FIELDS)
            .withIgnoredFields("customColoring", "dir", "drawLine", "east", "north", "eastNorthCacheKey")
            .withPrefabValues(ColorSpace.class, ColorSpace.getInstance(ColorSpace.CS_sRGB), ColorSpace.getInstance(ColorSpace.CS_LINEAR_RGB))
            .verify();
    }
}
```

# What error message or stack trace does EqualsVerifier give?
```
    [junit] WARNING: An illegal reflective access operation has occurred
    [junit] WARNING: Illegal reflective access by nl.jqno.equalsverifier.internal.reflection.FieldAccessor (file:/var/lib/jenkins/jobs/Java-EarlyAccess-JOSM/workspace/jdk/JDK10/test/lib/equalsverifier-2.4.1.jar) to field java.awt.color.ICC_ColorSpace.thisProfile
    [junit] WARNING: Please consider reporting this to the maintainers of nl.jqno.equalsverifier.internal.reflection.FieldAccessor
    [junit] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
    [junit] WARNING: All illegal access operations will be denied in a future release
```

# What did you expect?
No warning

# Which version of EqualsVerifier are you using?
2.4.1

# Please provide any additional information below.
Same issue with Java 9.0.1.

**Comment by jqno** [comment] 2018-01-16 07:43
Hi,

Thanks for liking the tweet ;).

I can reproduce your issue with the following classes:
https://github.com/jqno/equalsverifier-issuerepro/blob/issue-183/src/test/java/nl/jqno/equalsverifier/MyClass.java
https://github.com/jqno/equalsverifier-issuerepro/blob/issue-183/src/test/java/nl/jqno/equalsverifier/EqualsTest.java

Would you say that's a fair representation of your own code? Because I'm also getting some recursive data structure issues.

**Comment by don-vip** [comment] 2018-01-16 09:36
Yes, the whole test class is here: https://josm.openstreetmap.de/browser/josm/trunk/test/unit/org/openstreetmap/josm/data/gpx/WayPointTest.java

The class under test is here: https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/data/gpx/WayPoint.java

**Comment by jqno** [comment] 2018-01-16 15:15
OK, thanks. This will be easy enough to fix.
I wonder how many more classes there are that I've overlooked :).
I'm not sure when I'll be able to release that fix though. Hopefully during the weekend.

**Comment by jqno** [comment] 2018-01-19 10:19
I've made a fix for this. I hope to release it tomorrow.

**Comment by jqno** [comment] 2018-01-20 12:47
It's released!

**Closed as completed by jqno** 2018-01-20 12:47 UTC
Labels: accepted

**Comment by jqno** [comment] 2018-01-20 12:49
Note that you probably have to remove the `withPrefabValues` line to make it work. I'm sure you won't mind doing that, though ;)
