### ISSUE TITLE
EV fails when significant field of non-final class altered in finalizer

### ISSUE THREAD

**Issue by ssoloff** [jqno/equalsverifier#139] opened 2016-04-20 01:55 UTC
# What steps will reproduce the problem?

See the MCVE below.
# What is the code that triggers this problem?

_build.gradle_

``` gradle
apply plugin: 'java'

repositories {
    mavenCentral()
}

dependencies {
    testCompile 'junit:junit:4.12'
    testCompile 'nl.jqno.equalsverifier:equalsverifier:2.0.2'
}
```

_src/main/java/Foo.java_

``` java
import java.util.Arrays;

public class Foo {
    private byte[] value;

    public byte[] getValue() {
        return value;
    }

    public void setValue(final byte[] value) {
        if (this.value != null) {
            Arrays.fill(this.value, (byte) 0);
        }
        this.value = value;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == null) {
            return false;
        } else if (obj == this) {
            return true;
        } else if (obj.getClass() != getClass()) {
            return false;
        }

        final Foo other = (Foo)obj;
        return Arrays.equals(value, other.value);
    }

    @Override
    protected void finalize() throws Throwable {
        setValue(null);
        super.finalize();
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(value);
    }
}
```

_src/test/java/FooTest.java_

``` java
import nl.jqno.equalsverifier.EqualsVerifier;
import nl.jqno.equalsverifier.Warning;
import org.junit.Test;

public final class FooTest {
    @Test
    public void shouldImplementEqualsAndHashCode() {
        EqualsVerifier.forClass(Foo.class)
            .usingGetClass()
            .suppress(Warning.NONFINAL_FIELDS)
            .verify();
    }
}
```
# What error message or stack trace does EqualsVerifier give?

```
java.lang.AssertionError: Significant fields: equals does not use value, or it is stateless.
For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
    at nl.jqno.equalsverifier.EqualsVerifier.handleError(EqualsVerifier.java:381)
    at nl.jqno.equalsverifier.EqualsVerifier.verify(EqualsVerifier.java:367)
    at FooTest.shouldImplementEqualsAndHashCode(FooTest.java:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:112)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
# What did you expect?

`shouldImplementEqualsAndHashCode()` should pass.
# Which version of EqualsVerifier are you using?

See _build.gradle_ above.  Environment follows:

```
$ gradle --version

------------------------------------------------------------
Gradle 2.12
------------------------------------------------------------

Build time:   2016-03-14 08:32:03 UTC
Build number: none
Revision:     b29fbb64ad6b068cb3f05f7e40dc670472129bc0

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Linux 4.4.6-301.fc23.x86_64 amd64
```
# Please provide any additional information below.

Hi Jan,

I'm trying to introduce EV into a new codebase on which I recently started working and encountered the above failure while adding an EV unit test to a legacy class.  What makes this class different than any with which I've previously used EV is that it overrides `finalize()` and proceeds to alter the contents of an array instance field that is used in the implementations of `equals()` and `hashCode()`.  The MCVE above reproduces the problem exactly as I observed it in my production code.

I can get the test to pass if I do _any_ of the following in isolation:
- comment out the call to `setValue(null)` in the finalizer, or
- comment out the call to `Arrays.fill()` in `setValue()` (a more refined version of the previous case), or
- mark the class as `final`.

I did not debug EV too deeply, so I'm not 100% sure if this is an EV defect or user error on my part.  But it almost seems like EV is holding onto a reference to this instance field after the containing object is GCed, and _then_ performs its tests.  Of course, at this point, the contents of the array have been zeroed and presumably altered from what EV had originally set them to at the start of the test.

Any insight you can offer would be appreciated!

**Comment by jqno** [comment] 2016-04-20 05:58
Hi Steven,

I'm afraid I don't have a lot of insight for you at this point. I recreated the test project as you described, but for me, the test succeeds, both in IntelliJ and on the command-line using Gradle. My environment is different though:

```
------------------------------------------------------------
Gradle 2.7
------------------------------------------------------------

Build time:   2015-09-14 07:26:16 UTC
Build number: none
Revision:     c41505168da69fb0650f4e31c9e01b50ffc97893

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.11.4 x86_64
```

I'll try to upgrade to a more recent version of Gradle when I'm at work. (I'm on a train now; wifi is disappointing in here ;).) Although I can't imagine that will make much of a difference. I did try it on a JDK 1.7 (`1.7.0_79 (Oracle Corporation 24.79-b02)` to be precise) but it succeeds there, too.

I guess this is part of the fun of debugging code that uses finalizers :grimacing:

**Comment by jqno** [comment] 2016-04-20 06:45
Nope, succeeds with Gradle 2.12 too :).

**Comment by ssoloff** [comment] 2016-04-20 13:16
Of course there's a race condition... :unamused:

I added a five second sleep at the top of `finalize()` to ensure the test completes on the main thread before the finalizer thread can clear the array.  Sure enough, the test consistently passes on my machine.

Please let me see if I can come up with a more deterministic MCVE.  If I can't do that in the next few days, I'll close this issue.

**Comment by ssoloff** [comment] 2016-04-20 17:59
I switched from my VM to a physical machine and, as you observed, could not get the test to fail.  In an attempt to get finalization to run prior to where EV is performing its tests, I added two lines of code to the start of `SignificantFieldCheck.execute()`.  The diff follows (this is relative to the current `master` branch, not to the `equalsverifier-2.0.2` tag):

``` diff
diff --git a/src/main/java/nl/jqno/equalsverifier/FieldsChecker.java b/src/main/java/nl/jqno/equalsverifier/FieldsChecker.java
index f634f40..5719876 100644
--- a/src/main/java/nl/jqno/equalsverifier/FieldsChecker.java
+++ b/src/main/java/nl/jqno/equalsverifier/FieldsChecker.java
@@ -158,7 +158,10 @@ class FieldsChecker<T> implements Checker {
         }

         @Override
+        @edu.umd.cs.findbugs.annotations.SuppressWarnings("DM_GC")
         public void execute(FieldAccessor referenceAccessor, FieldAccessor changedAccessor) {
+            System.gc();
+            System.runFinalization();
             if (isCachedHashCodeField(referenceAccessor)) {
                 return;
             }
```

I then modified the MCVE to use my custom build of EV (in a sibling folder of the MCVE):

``` diff
diff --git a/build.gradle b/build.gradle
index 3e81f94..effb2e6 100644
--- a/build.gradle
+++ b/build.gradle
@@ -2,9 +2,12 @@ apply plugin: 'java'

 repositories {
     mavenCentral()
+    flatDir {
+        dirs '../equalsverifier/target'
+    }
 }

 dependencies {
     testCompile 'junit:junit:4.12'
-    testCompile 'nl.jqno.equalsverifier:equalsverifier:2.0.2'
+    testCompile 'nl.jqno.equalsverifier:equalsverifier:2.0.3-SNAPSHOT'
 }
```

On the physical machine where the test consistently passed, it now fails about 60% of the time.  It's still not deterministic (possibly because `gc()` and `runFinalization()` are not deterministic), but I'm hoping you will have the same experience and be able to observe a failure without having to run it more than four or five times. :pray:

**Comment by jqno** [comment] 2016-04-21 06:52
Haha, nice work :). I'll check it out later. I won't have a lot of time this weekend though, so it might be a few days before I get to it.

**Comment by ssoloff** [comment] 2016-04-21 13:30
No worries, Jan.  Given the non-deterministic nature of the bug and the questionable use of a finalizer in our code (for the use case we're trying to support, we should really be implementing the Dispose pattern via `AutoCloseable`), I'm happy with any time you can spend on this.

**Comment by jqno** [comment] 2016-05-03 08:02
I've looked at it a bit more, and I think I know what's going on. EqualsVerifier keeps a cache of objects that it can use to assign to fields in the class it's testing. The first time it comes across Foo's byte array, it constructs a byte array and assigns it to value. (Actually, it constructs two different ones, so it has something to do when calling equals.) The values in the cache are two one-element arrays: [1] and [2]. The next time it comes across Foo's value field, it just takes it directly from the cache.

Foo's finalizer, in the mean time, will call Arrays.fill on its value field, and set all its elements to zero. Since it's the reference in Foo is the same reference in the cache, it will mutate the objects in the cache. What happens next depends a little on chance, because of threads and the non-deterministic nature of finalizers, but at some point, both byte[] instances in the cache will be set to [0]. EqualsVerifier expects the references to be different, so this explains why EqualsVerifier fails. It only happens sometimes, because sometimes the finalizers run before the relevant check, and sometimes they run after.

I think it's up to you now to decide whether Foo should really be clearing those arrays. And it's up to me to make sure that EqualsVerifier makes a copy when it takes an object from the cache (and come up with a deterministic unit test for this :wink: ).

**Comment by ssoloff** [comment] 2016-05-03 12:19
Thanks for taking the time to research this, Jan!  Your findings make total sense.  I'm looking forward to the EV fix, but, as you suggested, we'll want to re-evaluate our design, as well.  I've been prototyping modifying our _real_ `Foo` to implement `AutoCloseable` and then to log a warning in the finalizer if the array in question has not been cleared (per Josh Bloch's recommendation), as it is now a programmer error for not explicitly closing the container resource.  But these things take time in a large code base. :smirk:

**Comment by jqno** [comment] 2016-05-08 15:58
Fixing this has proven a little harder than I thought, so it might take a while. Sorry about that :).

**Comment by ssoloff** [comment] 2016-05-08 21:52
Not a problem, Jan.  This isn't a blocker for us -- we simply have a test that's `@Ignore`d for a class that is unlikely to see any changes in its implementation of `equals()` and `hashCode()`.

**Comment by jqno** [comment] 2016-05-21 07:19
Hi Steven,

I have some sad news: I probably won't fix this issue.

I have been able to find some possible solutions for the problem itself, but none of them are simple. (I haven't implemented any of them fully yet, but they look promising.)
The real problem, however, is that I'm unable to come up with a reliable, reproduceable test to trigger this behaviour. I thought modifying values from within `equals` or `hashCode` itself would do the trick, but the behaviour is different enough that they break down when I apply the fixes I've come up with. In other words, they aren't usable to test this issue.
I'm not willing to make big changes for something I can't properly test, because the issue might slip back in in a later release.

I did, however, find a workaround that might be sufficient for your needs. If you mark the `value` field as `transient`, EV will simply skip the check that sometimes fails. You'll also have to use `.suppress(Warning.TRANSIENT_FIELDS)`, because when the GC doesn't run, EV would complain that a transient field was used in the `equals` contract.
I don't know if you can safely mark the field as `transient` in your code, because it does have some consequences for serialization. But it's something you could try, perhaps :).

**Comment by ssoloff** [comment] 2016-05-21 18:10
Hi Jan,

I totally understand not wanting to make such an architecturally-significant change without having proper tests in place.

Unfortunately, the class in question does implement `Serializable` and requires the array field to be part of the serialized representation.  However, I did want to try out your proposal to mark this field `transient` and verified it indeed works.  But this approach is equivalent to just using `withIgnoredFields()`, right?  Removing the field in question from the `equals()` and `hashCode()` implementations does not cause EV to fail the contract tests, which is the regression we were trying to protect against.  We didn't want to use `withIgnoredFields()` to avoid some other dev coming along a few months from now, accidentally screwing up how the array field is used in `equals()` or `hashCode()`, and having the tests happily continue to pass.

Anyway, I'm going to push harder for the correct long-term fix to this problem: replacing the clean-up in the finalizer with a proper Dispose pattern implementation.  In the short term, we'll have to internally debate what we're willing to sacrifice to get (at least some) value from the EV unit tests for this class.

Thanks again for the time you spent on this issue!  Please feel free to close it at your leisure.

**Comment by ssoloff** [comment] 2016-05-21 22:33
Jan, your suggestion of applying `transient` caused me to review the code in question after having not looked at it for a couple of weeks.  I had an epiphany of sorts related to a more satisfying workaround.  I simply created a test-specific subclass that overrides `finalize()` with an empty implementation.  Thus, the superclass implementation that modified the field is not called and the race condition is suppressed.

Using that test-specific subclass with EV results in a consistently-passing test, and more importantly, I verified it fails when I change the original class in a way that violates the equals contract.  I'm embarrassed I didn't think of this a month ago. :disappointed:

**Comment by jqno** [comment] 2016-05-22 09:06
Haha, sometimes solutions are so simple you just don't see them :). I didn't think of it either. (Didn't think of `withIgnoredFields` either, btw, focused as I was on a class with only the one field :).) I'm glad we were able to rubber duck our way out of this in the end though.

**Closed as completed by jqno** 2016-05-22 09:06 UTC
Labels: accepted
