### ISSUE TITLE
Provide an option to supress superclass equals check if superclass is abstract.

### ISSUE THREAD

**Issue by tiwarisarthak** [jqno/equalsverifier#749] opened 2022-12-29 10:29 UTC
**Is your feature request related to a problem? Please describe.**
Currently, superclass checks cannot be skipped if both superclass and test class override the ```equals``` method. However, in cases when the superclass is ```abstract```, we can give an option to skip the equals test for superclass and test class check. This is because in real life scenarios, we barely use the abstract class ```equals``` method, and the override is just to ensure completeness. If we are using ```Equalsverifier``` as of today, we have to add ```canEqual``` method in abstract classes which increases boiler plate code and is mostly annoying as we don't allow abstract types to be used anyways.

**Describe the solution you'd like**
Add an option in ```Warning``` to suppress superclass equals check if superclass is abstract.

**Describe alternatives you've considered**
Currently, we can handle this by adding a ```canEqual``` method in equals of both classes, but that is a complex solution to satisfy the constraint.

**Additional context**
This is in line with the current ```Warning.NULL_FIELDS``` suppression. Although it should be upheld, we allow to skip it as some people will prevent ```NullPointerException``` from occurring by having validation in constructor/annotation.

**Comment by jqno** [comment] 2022-12-30 12:37
Interesting idea, but how is it different from `Warning.STRICT_INHERITANCE`?

**Comment by tiwarisarthak** [comment] 2023-01-01 17:40
Afaik, ```Warning.STRICT_INHERITANCE``` only affects subclasses and not superclass?

**Comment by jqno** [comment] 2023-01-04 13:26
I tried to reproduce your situation, and I think in this case, you shouldn't use `withRedefinedSuperclass()` at all, since, as you mentioned, you barely use the abstract class's `equals` methods. `withRedefinedSuperclass()` is intended to check that you did the `canEqual()` thing correctly, but that's not the way you intend to use `equals` in this case.

If you do this, I think you still need to suppress `Warning.STRICT_INHERITANCE` though.

**Comment by jqno** [comment] 2023-02-16 10:08
I'm closing this issue now. If this is still a problem, please post a comment and we can re-open.

**Closed as completed by jqno** 2023-02-16 10:08 UTC
