### ISSUE TITLE
Documentation on "Mutability: equals depends on mutable field" could be misinterpreted 

### ISSUE THREAD

**Issue by PaulienVa** [jqno/equalsverifier#360] opened 2020-11-18 08:12 UTC
# What steps will reproduce the problem?
Implement the equals verifier test for a mutable object

# What error message or stack trace does EqualsVerifier give?

> There are three ways to solve this:

> - Make your field final. This is the preferred solution.
> - Add an @Immutable annotation to your class if you know that the class is immutable, but the fields cannot be final for some reason.
> - Suppress Warning.NONFINAL_FIELDS if your class has to be mutable. This is not recommended.
> Note: Unfortunately, EqualsVerifier cannot detect if your fields are truly immutable, which is what’s actually needed here. It can only see if fields are final, or if the class has an @Immutable annotation.

# What did you expect?
The problem here is that the list will suggest a preferred way of fixing the problem, first try to make the object immutable, then if that is not fixing it, use (a) @Immutable annotation and if that does not work use the `SuppressWarning` in your test.

It would be better to specify which @Immutable is correct and when to use it. For the `SuprressWarning` clause, maybe add a code example:
```
EqualsVerifier.forClass(MyClass.class).suppress(SuppressWarning.NONFINAL_FIELD).verify()
```

# Which version of EqualsVerifier are you using?
3.1.13

# Please provide any additional information below.

**Comment by jqno** [comment] 2020-11-18 10:01
If I understand correctly, the issue is in the website, and not in the error message that EqualsVerifier itself outputs, right?

To clarify for future me; what you told me on twitter is that junior team members saw this text and decided to just slap `@Immutable` annotations on everything, without understanding that even though those classes had final fields, they weren't actually immutable. Also, they chose Spring Data's `@Immutable` annotation, where a different supplier may have been more appropriate.

The documentation should be clearer about when `@Immutable` is appropriate. This applies to [this errormessage page](https://jqno.nl/equalsverifier/errormessages/mutability-equals-depends-on-mutable-field/) and [this manual page](https://jqno.nl/equalsverifier/manual/immutability/) (and perhaps others as well?)

**Comment by PaulienVa** [comment] 2020-11-19 20:30
True, maybe add documentation on which `@immutable` to use if you want to use it and maybe add an example for the Suppress Warning.NONFINAL_FIELDS. I had to look through the docs myself before finding it. It was not that obvious. I first naively thought that it was an annotation `@SuppressWarnings` such as with Sonar  ;)

**Comment by jqno** [comment] 2020-11-20 05:34
Ah ok, didn't realize that it wasn't obvious. I'll have to add examples to a lot of pages then 😅. But that's fine!

Can you tell me why Spring Data's `@Immutable` is not appropriate? Equalsverifier is built so that it doesn't matter where the annotation comes from, as long as it's called `@Immutable`. I could add some generic message about choosing carefully, but I'm not sure I can actually give more guidance than that.

**Comment by PaulienVa** [comment] 2020-11-20 05:44
Ah fair point, Spring Data was not appropriate for us. It certainly might be in other projects ;)
I would expect Spring Data on entity class for example if they are managed by Spring Data. That was not the case for us. For us, a custom @Immutable would have been more correct. However the classes were meant not be final in our case, so the suppress warnings were better ;)

**Comment by jqno** [comment] 2020-11-22 12:43
I've updated the documentation. Can you check if you agree with how it's written now?

Relevant sections: https://jqno.nl/equalsverifier/errormessages/mutability-equals-depends-on-mutable-field/ and https://jqno.nl/equalsverifier/manual/immutability/

**Comment by PaulienVa** [comment] 2020-11-23 07:22
This is better, the example helps a lot I think 👍

**Comment by jqno** [comment] 2020-11-23 07:24
Thanks! I'll close the issue then.

**Closed as completed by jqno** 2020-11-23 07:24 UTC
Labels: accepted
